- name: Check if source SSH key exists
  stat:
    path: "{{ source_key }}"
  register: source_key_stat

- name: Ensure .ssh directory exists
  file:
    dest: "{{ dest_key | dirname }}"
    mode: 0700
    state: directory

- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: 0600
  when: source_key_stat.stat.exists

- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: 0644
  when: source_key_stat.stat.exists

- name: Set authorized key from file
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', dest_key + '.pub') }}"
  when: source_key_stat.stat.exists
  ignore_errors: yes
