packages:
  - pnpm
  - typescript

brew_cask_packages:
  - google-chrome
  - microsoft-edge
  - firefox
  - google-drive
  - slack
  - visual-studio-code
  - docker
  - vlc
  - postman
  - nikitabobko/tap/aerospace

brew_packages:
  - go
  - git
  - lazygit
  - stow

vscode_extensions:
  - dbaeumer.vscode-eslint
  - GitHub.copilot
  - eamodio.gitlens
  - yzhang.markdown-all-in-one
  - zhuangtongfa.material-theme
  - bierner.markdown-mermaid
  - esbenp.prettier-vscode
  - vscodevim.vim
